version: "0.6.0+1.19.4"
showItemEmcOrigin: false
showEnchantedBookRepairCost: true
enchantmentEmcConstant: "3260"
emcInMultiplier: "1"
emcOutMultiplier: "1"
mapper.enabled: true
transmutationTable.animated: true
transmutationTable.floorButton: false
antiMatterRelay.onlyAcceptFuelItems: false